### ISSUE TITLE
Advice for dealing with larger-than-memory data

### ISSUE THREAD

**Issue by SultanOrazbayev** [gchq/annchor#12]
I am interested in applying this method on data that would not fit into memory. Could you advise on what could be an efficient approach? (other than applying in parallel on all combinations of chunks that do fit in memory)

**Comment by jh83775** [comment]
Good question. One thing that comes to mind - is it possible to get your data when you make calls to the metric? The data set in python would be an array of indices to the actual data (stored elsewhere); then when you call dist(i,j), your function could grab your actual data X[i], X[j], compute the distance, and get rid of them from memory. In this way you never have to hold the entire dataset in memory, only two points at a time (or more depending on parallelisation, but much less than the full dataset).
Of course, this would add some overhead to computing the distance metric.

**Comment by SultanOrazbayev** [comment]
Ah, great, thanks, this should work for my case!

**Comment by SultanOrazbayev** [comment]
Sorry for re-opening, but wanted to clarify: without access to data how would `annchor` know the features for computing the 'fast' metric?

**Comment by jh83775** [comment]
The features for computing the fast metric come from upper/lower bounds derived from distances to the anchor points. So we call the slow metric a few times (to get distances from all the data points to the anchor points), and then generate the features. If our data set is size `nx`, and we specify `na` anchor points, then we make `na*nx` calls to the metric to compute the features. Coming back to your question: we do need access to the data to gather the features, but this can be done at metric query time if the data is too large to fit in memory.

**Comment by SultanOrazbayev** [comment]
Aaah, ok, I understand now how it works... I thought it was doing the calculations in a different way (using feature similarity to the anchor points as an input to the fast distance metric), but with this approach wrapping data queries into distance function resolves the memory problem in my case. Thank you for the explanation!
